// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOKycgIA24W3PErg_fGAnGq0SVAuglsrw',
    appId: '1:449212592490:web:b5f749203a0d8b3234b513',
    messagingSenderId: '449212592490',
    projectId: 'bookapp-707cb',
    authDomain: 'bookapp-707cb.firebaseapp.com',
    storageBucket: 'bookapp-707cb.appspot.com',
    measurementId: 'G-7NDX9VBM6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFAH0SP8hdPf6C4Dmi_0PCYWKa2my1Ys',
    appId: '1:449212592490:android:7730d6c86eaea93434b513',
    messagingSenderId: '449212592490',
    projectId: 'bookapp-707cb',
    storageBucket: 'bookapp-707cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfH8RQLwWQo0um7BCGclAHT2ZVDHt7GZI',
    appId: '1:449212592490:ios:dec5c8834151274034b513',
    messagingSenderId: '449212592490',
    projectId: 'bookapp-707cb',
    storageBucket: 'bookapp-707cb.appspot.com',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfH8RQLwWQo0um7BCGclAHT2ZVDHt7GZI',
    appId: '1:449212592490:ios:3cebe3a7fc271bed34b513',
    messagingSenderId: '449212592490',
    projectId: 'bookapp-707cb',
    storageBucket: 'bookapp-707cb.appspot.com',
    iosBundleId: 'com.example.bookapp.RunnerTests',
  );
}
